fix: missing padding and gaus commmands
!topaz denoise3d -o ./ volumes /kaggle/working/tmp.mrc -m unet-3d-20a -s 96 -p 48

Traceback (most recent call last):
  File "/opt/conda/bin/topaz", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/topaz/main.py", line 148, in main
    args.func(args)
  File "/opt/conda/lib/python3.10/site-packages/topaz/commands/denoise3d.py", line 95, in main
    print(f'# denoising {total} tomograms with patch size={args.patch_size} and padding={args.padding}', file=sys.stderr)
AttributeError: 'Namespace' object has no attribute 'padding'